services:
  trash-db:
    image: postgres:13.4-alpine
    restart: always
    environment:
      - POSTGRES_DB=${PSQL_DB_NAME}
      - POSTGRES_USER=${PSQL_USER_NAME}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
    ports:
      - ${PSQL_PORT}:5432
    volumes:
      - ./data:/docker-entrypoint-initdb.d